@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title WarmHome System

LAYOUT_WITH_LEGEND()

Person(user, "User", "A user of the warmhouse service")
Person(admin, "Administrator", "An administrator warmhouse service")

System_Boundary(system, "Warmhome System") {
    Container(user_iteraction, "User Iteraction", "", "Profile of home and scenarios")
    Container(admin_panel, "Admin Panel", "", "Manage users data")
    Container(control_api, "Control API", "", "Central control logic and event processing")
    ContainerQueue(kafka, "Message broker", "Apache Kafka", "Real-time event streaming")
    Container(telemetry, "Telemetry", "", "Telemetry from controlers and sensors")
}

System_Ext(devices, "Devices", "IoT devices")
System_Ext(sensors, "Sensors", "IoT sensors")

' User interactions
Rel(user, user_iteraction, "Send commands and get information to system", "HTTPS")
Rel(admin, admin_panel, "Manage configurations via", "Admin Panel")
Rel(admin_panel, user_iteraction,  "Edit users data",  "HTTPS")

' User interactions to System
Rel(user_iteraction, kafka, "Send events for control devices, get query from sensor and get result of scenarios", "MQTT")
Rel(admin_panel, kafka, "Send admins commands to divices", "MQTT")

' Control system
Rel(kafka, control_api, "Get events for control devices", "MQTT")
Rel(kafka, telemetry, "Get gueries to telemetry", "MQTT")

' IoT 
Rel(control_api, devices, "Send commands to controller", "HTTPS")
Rel(telemetry, sensors, "Send query by value", "HTTPS")

@enduml