@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram for User Iteraction

LAYOUT_WITH_LEGEND()

Person(user, "User", "Controls and monitors smart home devices")
Person(admin, "Admin", "Administrator of system")

System_Boundary(SmartHomeSystem, "User iteraction") {
    Container(api_gateway, "API Gateway", "Kong", "Routes requests to appropriate services")
    
    Container(home_profile, "Home Profile", , "list of devices and scenarios")
    Container(admin_panel, "Admin panel", , "web panel for administrator")
    
    ContainerDb(home_profile_db, "Home Profile Database", "PostgreSQL", "Stores home configurations and user information")
    ContainerDb(services_db, "Service Database", "PostgreSQL", "Stores service configurations and informations")
    
}

ContainerQueue(kafka, "Message broker", "Apache Kafka", "Real-time event streaming")

' Relations
Rel(user, api_gateway, "Controls devices via", "REST/HTTPS")
Rel(admin, api_gateway, "Administration of system", "REST/HTTPS")
Rel(api_gateway, home_profile, "Configures system via", "REST/HTTPS")
Rel(api_gateway, admin_panel, "Configures system via", "REST/HTTPS")

Rel(home_profile, home_profile_db, "Reads/Writes data")
Rel(admin_panel, services_db, "Reads/Writes data")

Rel(home_profile, kafka, "Send commands and events", "MQTT")
Rel(admin_panel, kafka, "Send commands and events", "MQTT")

@enduml