name: PlantUML Diagrams

on:
  push:
    branches:
      - warmhouse
  pull_request:
    branches:
      - main

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install PlantUML
      run: sudo apt-get install plantuml

    - name: Generate Diagrams
      run: |
        echo "Run generate diagrams"
        plantuml -verbose diagrams/context/*.puml
        plantuml -verbose diagrams/container/*.puml
        plantuml -verbose diagrams/component/*.puml
        plantuml -verbose diagrams/code/*.puml
    
    - name: Commit Diagrams
      run: |
        git config --local user.email "demkov.boris@gmail.com"
        git config --local user.name "AIofHuman"
        git add diagrams/**/*.png
        git commit -m "Automated diagram generation"
        git push origin warmhouse
      if: success()
